services:
  - type: web
    name: fwc-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python scripts/seed_db.py
    startCommand: >
      gunicorn 'wsgi:app' --bind 0.0.0.0:$PORT

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: business_school_prod_database
          property: connectionString
